name: CI
env:
  BUILD_CONFIGURATION: Release
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install gcc make g++ libtool cmake
    - name: Build
      run: "bash ci.sh"
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set MSBuild env
      uses: microsoft/setup-msbuild@v1.1
    - name: Build for engine
      run: "bash ci.sh"
